---
- name: Install ArgoCD with NodePort
  hosts: master
  become: true
  vars:
    kube_user: "{{ target_user | default('cloud_user') }}"
    chart_name: "{{ argocd_chart_name | default('argo/argo-cd') }}"
    chart_version: "{{ argocd_chart_version | default('') }}"
    release_name: "{{ argocd_release_name | default('argocd') }}"
    argocd_ns: "{{ argocd_namespace | default('argocd') }}"
    nodeport: "{{ argocd_nodeport | default('30080') }}"
  tasks:

    - name: Create namespace if not exists
      ansible.builtin.shell: |
        set -o pipefail
        kubectl create namespace {{ argocd_ns }} \
          --dry-run=client -o yaml | kubectl apply -f -
      environment:
        KUBECONFIG: /home/{{ kube_user }}/.kube/config
      become: true
      become_user: "{{ kube_user }}"
      changed_when: false
    - name: Check if Helm release exists
      ansible.builtin.shell: |
        set -o pipefail
        helm list -n {{ argocd_ns }} | grep -q {{ release_name }}
      delegate_to: localhost
      become: false
      register: release_check
      failed_when: false
      changed_when: false
    - name: Clean up existing ArgoCD resources if needed
      ansible.builtin.shell: |
        kubectl delete all --all -n {{ argocd_ns }} --ignore-not-found=true
      environment:
        KUBECONFIG: /home/{{ kube_user }}/.kube/config
      become: true
      become_user: "{{ kube_user }}"
      when: release_check.rc != 0
      changed_when: false
    - name: Install ArgoCD with NodePort
      ansible.builtin.shell: |
        helm install {{ release_name }} {{ chart_name }} \
          --namespace {{ argocd_ns }} \
          --set server.service.type=NodePort \
          --set server.service.nodePortHttp={{ nodeport }} \
          --set server.insecure=true \
          --create-namespace \
          {% if chart_version %}--version {{ chart_version }}{% endif %}
      delegate_to: localhost
      become: false
      when: release_check.rc != 0
      changed_when: release_check.rc != 0
    - name: Show Helm release status
      ansible.builtin.shell: |
        helm status {{ release_name }} -n {{ argocd_ns }}
      delegate_to: localhost
      become: false
      register: helm_status
      changed_when: false
    - name: Display Helm status
      ansible.builtin.debug:
        var: helm_status.stdout_lines
    - name: Get NodePort service details
      ansible.builtin.shell: |
        kubectl get svc -n {{ argocd_ns }} -o wide
      environment:
        KUBECONFIG: /home/{{ kube_user }}/.kube/config
      become: true
      become_user: "{{ kube_user }}"
      register: service_details
      changed_when: false
    - name: Get ArgoCD admin password
      ansible.builtin.shell: |
        set -o pipefail
        kubectl -n {{ argocd_ns }} get secret \
          argocd-initial-admin-secret \
          -o jsonpath="{.data.password}" | base64 -d
      environment:
        KUBECONFIG: /home/{{ kube_user }}/.kube/config
      become: true
      become_user: "{{ kube_user }}"
      register: argocd_password
      changed_when: false
      failed_when: false
    - name: Show ArgoCD access details
      ansible.builtin.debug:
        msg: |
          ArgoCD Service Details:
          {{ service_details.stdout }}

          ArgoCD Access:
          URL: http://{{ ansible_default_ipv4.address }}:{{ nodeport }}
          Username: admin
          {% if argocd_password.stdout %}Password: {{ argocd_password.stdout }}{% else %}Password: Check secret manually{% endif %}

          Note: ArgoCD is configured in insecure mode (HTTP) for
          Gitea webhook compatibility.
          Gitea webhook URL:
            http://{{ ansible_default_ipv4.address }}:{{ nodeport }}\
            /api/webhook
