---
- name: Kubernetes Cluster Maintenance Automation
  hosts: localhost
  gather_facts: false
  vars:
    maintenance_action: "{{ action | default('status') }}"
  tasks:
    - name: Show maintenance options
      ansible.builtin.debug:
        msg: |
          Kubernetes Cluster Maintenance Tool

          Available actions:
          - shutdown: Drain nodes before 4-hour window
          - startup: Uncordon nodes after restart
          - status: Show current node status

          Current action: {{ maintenance_action }}
    - name: Show cluster status
      ansible.builtin.command: >
        kubectl get nodes -o wide --kubeconfig ~/.kube/config
      delegate_to: localhost
      become: false
      register: cluster_status
      when: maintenance_action == 'status'
      changed_when: false
    - name: Display cluster status
      ansible.builtin.debug:
        var: cluster_status.stdout_lines
      when: maintenance_action == 'status'

- name: Execute shutdown preparation
  import_playbook: node-shutdown.yml
  when: action | default('status') == 'shutdown'

- name: Execute startup recovery
  import_playbook: node-startup.yml
  when: action | default('status') == 'startup'
