- name: Get internal IP addresses for ArgoCD integration
  hosts: all
  gather_facts: true
  tasks:
    - name: Display internal IP information
      ansible.builtin.debug:
        msg: |
          Host: {{ inventory_hostname }}
          Internal IP: {{ ansible_default_ipv4.address }}

          {% if inventory_hostname in groups['workers'] %}
          Gitea URL for ArgoCD:
          http://{{ ansible_default_ipv4.address }}:3000
          {% endif %}

- name: ArgoCD Integration Summary
  hosts: localhost
  gather_facts: false
  vars:
    gitea_host: >
      {{ groups['workers'][0] if groups['workers'] is defined else 'N/A' }}
  tasks:
    - name: Show ArgoCD integration summary
      ansible.builtin.debug:
        msg: |
          =================================================
          ArgoCD Integration Information
          =================================================

          Gitea Host: {{ gitea_host }}
          {% if gitea_host != 'N/A' %}
          Gitea Internal IP:
          {{ hostvars[gitea_host].ansible_default_ipv4.address }}

          Use this URL in ArgoCD:
          http://{{ hostvars[gitea_host].ansible_default_ipv4.address }}:3000/username/repo.git
          {% else %}
          No worker nodes found in inventory
          {% endif %}

          =================================================
