- name: Configure Join Commands on Master Node
  hosts: master
  become: true
  tasks:
    - name: Retrieve Join Command
      ansible.builtin.command: kubeadm token create --print-join-command
      changed_when: false
      register: join_command_raw
    - name: Set Join Command
      ansible.builtin.set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"
    - name: Check API server is listening
      ansible.builtin.command: netstat -tlnp | grep :6443
      register: api_server_status
      failed_when: false
      changed_when: false
    - name: Show API server status
      ansible.builtin.debug:
        var: api_server_status.stdout_lines
- name: Join Worker Nodes
  hosts: workers
  become: true
  vars:
    kube_user: "{{ target_user | default('cloud_user') }}"
  tasks:
    - name: Debug master host information
      ansible.builtin.debug:
        msg: >
          Master host: {{ hostvars[groups['master'][0]].ansible_host | default(groups['master'][0]) }}

    - name: Remove existing containerd config
      ansible.builtin.file:
        path: /etc/containerd/config.toml
        state: absent
    - name: Generate new containerd config
      ansible.builtin.shell: >
        containerd config default > /etc/containerd/config.toml

      changed_when: false
    - name: Enable CRI plugin in containerd
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: 'disabled_plugins = \["cri"\]'
        replace: 'disabled_plugins = []'
    - name: Configure systemd cgroup driver
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'
    - name: Restart containerd service
      ansible.builtin.systemd:
        name: containerd
        state: restarted
        enabled: true
        daemon_reload: true
    - name: Wait for containerd to be ready
      ansible.builtin.wait_for:
        path: /var/run/containerd/containerd.sock
        timeout: 30
    - name: Join worker to cluster
      ansible.builtin.shell: |
        {{ hostvars[groups['master'][0]].join_command }} >> node_joined.log
      args:
        chdir: /home/{{ kube_user }}
        creates: node_joined.log
      changed_when: false
