---
- name: Reset worker nodes first
  hosts: workers
  become: true
  tasks:
    - name: Reset worker node
      ansible.builtin.command: kubeadm reset --force
      failed_when: false
      changed_when: true
    - name: Clean up worker files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/kubernetes
        - /etc/cni/net.d
    - name: Stop kubelet
      ansible.builtin.systemd:
        name: kubelet
        state: stopped
      failed_when: false

- name: Reset master node
  hosts: master
  become: true
  tasks:
    - name: Reset master node
      ansible.builtin.command: kubeadm reset --force
      failed_when: false
      changed_when: true
    - name: Clean up master files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/kubernetes
        - /var/lib/etcd
        - /home/{{ target_user | default('cloud_user') }}/.kube
    - name: Recreate kubernetes directory
      ansible.builtin.file:
        path: /etc/kubernetes
        state: directory
        mode: '0755'

- name: Clean up container images
  hosts: all
  become: true
  tasks:
    - name: Stop containerd
      ansible.builtin.systemd:
        name: containerd
        state: stopped
    - name: Remove container images
      ansible.builtin.shell: |
        rm -rf /var/lib/containerd/*
      changed_when: true
    - name: Start containerd
      ansible.builtin.systemd:
        name: containerd
        state: started

- name: Summary
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Show reset summary
      ansible.builtin.debug:
        msg: |-
          =================================================
          Kubernetes Cluster Reset Complete
          =================================================

          ✅ Workers reset first
          ✅ Master reset after workers
          ✅ Container images cleaned up
          Cluster is ready for fresh initialization.

          =================================================
