---
- name: Drain worker nodes first
  hosts: workers
  become: true
  vars:
    kube_user: "{{ target_user | default('cloud_user') }}"
  tasks:
    - name: Get node name
      ansible.builtin.command: hostname
      register: node_name
      changed_when: false
    - name: Drain worker node
      ansible.builtin.command: >
        kubectl drain {{ node_name.stdout }}
        --ignore-daemonsets --delete-emptydir-data
        --force --timeout=300s
      environment:
        KUBECONFIG: /home/{{ kube_user }}/.kube/config
      delegate_to: "{{ groups['master'][0] }}"
      become: true
      become_user: "{{ kube_user }}"
      register: drain_result
      failed_when: false
      changed_when: "'drained' in drain_result.stdout"
    - name: Show worker drain result
      ansible.builtin.debug:
        msg: |
          Worker {{ node_name.stdout }} drain status:
          {% if drain_result.rc == 0 %}
          ✅ Successfully drained
          {% else %}
          ⚠️ Drain completed with warnings (RC: {{ drain_result.rc }})
          {% endif %}

- name: Drain master node last
  hosts: master
  become: true
  vars:
    kube_user: "{{ target_user | default('cloud_user') }}"
  tasks:
    - name: Get master node name
      ansible.builtin.command: hostname
      register: master_name
      changed_when: false
    - name: Drain master node
      ansible.builtin.command: >
        kubectl drain {{ master_name.stdout }}
        --ignore-daemonsets --delete-emptydir-data
        --force --timeout=300s
      environment:
        KUBECONFIG: /home/{{ kube_user }}/.kube/config
      become: true
      become_user: "{{ kube_user }}"
      register: master_drain_result
      failed_when: false
      changed_when: "'drained' in master_drain_result.stdout"
    - name: Show master drain result
      ansible.builtin.debug:
        msg: |
          Master {{ master_name.stdout }} drain status:
          {% if master_drain_result.rc == 0 %}
          ✅ Successfully drained
          {% else %}
          ⚠️ Drain completed with warnings (RC: {{ master_drain_result.rc }})
          {% endif %}
- name: Summary
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Show shutdown summary
      ansible.builtin.debug:
        msg: |-
          =================================================
          Kubernetes Node Shutdown Preparation Complete
          =================================================

          ✅ Workers drained first
          ✅ Master drained last
          All nodes ready for 4-hour shutdown window.

          =================================================
